### ISSUE TITLE
Are unit-tests all green?

### ISSUE THREAD

**Issue by chester89** [zcsizmadia/ZCS.Utf8Json#24]
We recently had to make a minor tweak to this library and wanted to run all tests.
Some of them failed - the ones that test float/decimal behaviour. They also failed before we made the changes.
Is this ok? We tried on Mac and Windows

**Comment by chester89** [comment]
![utf8-json-failed-tests](https://user-images.githubusercontent.com/190332/222168546-6e3ca47f-4212-4cac-97e8-82c75fe89dee.jpg)

**Comment by zcsizmadia** [comment]
Maybe some localization issue, the selected country/region has different floating point formatting?
